# Shared config for the lab. Source me; don't run me.
#
# The whole lab lives in ONE fake VM (OpenVidu/openvidu-fake-vm) with the fixed IP
# 10.5.0.3, because the public wildcard DNS entry playground.openvidu-local.dev
# resolves exactly there — so the deployment gets a real domain + a real trusted
# TLS certificate with zero DNS/hosts tricks.
#
# No credentials are hard-coded here. up.sh generates the secrets at first run into
# .state/lab.env (git-ignored) and sources them via this file. Nothing to reuse
# anywhere else — this is a throwaway local lab on a link-local-only domain.

LAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="$LAB_DIR/.state"

# fake-vm checkout: cloned INSIDE the repo by up.sh, so the lab is self-contained.
# Override with FAKE_VM_DIR if you keep it elsewhere.
FAKE_VM_DIR="${FAKE_VM_DIR:-$LAB_DIR/openvidu-fake-vm}"
# Pinned to a tagged release so a future fake-vm change can never alter the lab.
# (v0.1.0 == commit ef5e57c.) A branch name or commit SHA also works here.
FAKE_VM_REF="${FAKE_VM_REF:-v0.1.0}"

VM_IP="10.5.0.3"
DOMAIN="playground.openvidu-local.dev"
# Pinning OpenVidu pins its ENTIRE stack: the installer bakes in exact image tags
# for openvidu-server, egress/ingress, grafana, mimir, loki, prometheus, redis,
# mongo, minio, caddy and docker/compose. See VERSIONS.md.
OV_VERSION="${OV_VERSION:-3.8.0}"
NETWORK="openvidu"

# Non-secret identifiers (safe to keep in the repo).
LK_KEY="key1"
GRAFANA_ADMIN="grafanaadmin"
GRAFANA_URL="https://${DOMAIN}/grafana"

# Docker images used for the host-independent tooling (no local binaries needed).
# Pinned by immutable digest so the lab behaves identically forever, regardless of
# what the :latest tags point to later. Human-readable versions are in the comments
# and VERSIONS.md. The MCP digest below MUST match the one hard-coded in the two
# mcp/*/.mcp.json files (Claude reads those directly and can't see this variable).
MCP_IMAGE="${MCP_IMAGE:-grafana/mcp-grafana@sha256:f21a19cebbfa7c3a76ef1746171e5ffc3601064e432f593e7c6cb526e5216e5f}"   # mcp-grafana (devel, 2026-08)
LK_IMAGE="${LK_IMAGE:-livekit/livekit-cli@sha256:c118853d349f20ab043df2eb3e88a17ce55555bb79b5206fda907cd82a28d962}"      # lk 2.18.2
FFMPEG_IMAGE="${FFMPEG_IMAGE:-jrottenberg/ffmpeg@sha256:50171be54480baa9371be135493b034a9e08d2ff54eb873ce99963f12a24a187}"  # ffmpeg 8.0

# Secrets (LK_SECRET, GRAFANA_PASS, GRAFANA_TOKEN) are generated by up.sh into
# .state/lab.env and are NEVER committed. Source them if present.
[ -f "$STATE_DIR/lab.env" ] && . "$STATE_DIR/lab.env"

# fake-vm network overrides: the VM must live on a subnet that CONTAINS 10.5.0.3.
export FAKE_VM_NETWORK="$NETWORK"
export FAKE_VM_SUBNET="10.5.0.0/24"
export FAKE_VM_GATEWAY="10.5.0.1"
export FAKE_VM_IP_PREFIX="10.5.0"
# The pull-through registry lives on fake-vm's own network, unreachable from ours.
export FAKE_VM_NO_REGISTRY=1

# Run a command inside the VM (as ubuntu, passwordless sudo available).
vmssh() { "$FAKE_VM_DIR/fake-vm.sh" ssh "$VM_IP" "$@"; }

# The LiveKit CLI, containerised so no host install is needed. Runs on the lab
# network so it can reach the SFU at 10.5.0.3. Extra `docker run` flags may be
# passed before a literal `--` , then the lk args: lk_docker -v a:b -- load-test ...
lk_docker() {
  local extra=()
  while [ $# -gt 0 ] && [ "$1" != "--" ]; do extra+=("$1"); shift; done
  [ "${1:-}" = "--" ] && shift
  docker run --rm --network "$NETWORK" "${extra[@]}" "$LK_IMAGE" "$@"
}
